# Exported from Render on 2025-04-30T21:25:42Z
version: "1"

services:
  - type: web
    name: blunderfixer-api
    runtime: python
    repo: https://github.com/mattslight/blunderfixer-api
    plan: starter
    envVars:
      - key: STOCKFISH_PATH
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ENV
        value: production
        sync: true
    region: frankfurt
    buildCommand: ./render-build.sh && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    domains:
      - api.blunderfixer.com

jobs:
  - type: cron
    name: sync-all
    repo: https://github.com/mattslight/blunderfixer-api
    schedule: "*/15 * * * *" # every 5 min (UTC)
    plan: free
    command: |
      curl -fsS -X POST \
           https://api.blunderfixer.com/sync_all
