"""Add reason field to DrillHistory

Revision ID: 1412abd069b5
Revises: d968b73b020a
Create Date: 2025-06-03 13:52:14.627823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1412abd069b5'
down_revision: Union[str, None] = 'd968b73b020a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drillhistory', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drillhistory', 'reason')
    # ### end Alembic commands ###
