"""add themes to drillposition

Revision ID: 76f57ce66225
Revises: 82c83a8ff95c
Create Date: 2025-06-13 19:36:09.663627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76f57ce66225'
down_revision: Union[str, None] = '82c83a8ff95c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drillposition', sa.Column('themes', sa.JSON(), server_default='[]', nullable=False))
    op.alter_column('drillposition', 'winning_lines',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drillposition', 'winning_lines',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('drillposition', 'themes')
    # ### end Alembic commands ###
