"""Add comments and fix indexing

Revision ID: 7edd4ec71931
Revises:
Create Date: 2025-05-22 11:38:39.242664

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7edd4ec71931"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "archivemonth", "username", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("archivemonth", "month", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "archivemonth", "fetched_at", existing_type=sa.DATETIME(), nullable=True
    )
    op.alter_column(
        "archivemonth", "processed", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column("game", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("game", "url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("game", "played_at", existing_type=sa.DATETIME(), nullable=True)
    op.alter_column("game", "time_class", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("game", "time_control", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("game", "result", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("game", "eco", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("game", "pgn", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("job", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("job", "action", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("job", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("job", "total", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("job", "processed", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("job", "created_at", existing_type=sa.DATETIME(), nullable=True)
    op.alter_column("job", "updated_at", existing_type=sa.DATETIME(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("job", "updated_at", existing_type=sa.DATETIME(), nullable=False)
    op.alter_column("job", "created_at", existing_type=sa.DATETIME(), nullable=False)
    op.alter_column("job", "processed", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("job", "total", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("job", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("job", "action", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("job", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("game", "pgn", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("game", "eco", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("game", "result", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("game", "time_control", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("game", "time_class", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("game", "played_at", existing_type=sa.DATETIME(), nullable=False)
    op.alter_column("game", "url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("game", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "archivemonth", "processed", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "archivemonth", "fetched_at", existing_type=sa.DATETIME(), nullable=False
    )
    op.alter_column("archivemonth", "month", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "archivemonth", "username", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
