"""Add archived flag to DrillPosition

Revision ID: 95063c8527c1
Revises: 1412abd069b5
Create Date: 2025-06-04 14:33:16.528302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95063c8527c1'
down_revision: Union[str, None] = '1412abd069b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drillposition', sa.Column('archived', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drillposition', 'archived')
    # ### end Alembic commands ###
