"""add last_played_at to DrillPosition

Revision ID: a4370e98dae0
Revises: 7fbdd671b8fc
Create Date: 2025-06-05 02:04:03.727554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4370e98dae0'
down_revision: Union[str, None] = '7fbdd671b8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drillposition', sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drillposition', 'last_played_at')
    # ### end Alembic commands ###
