"""add material counts to DrillPosition

Revision ID: aff449acc12b
Revises: 
Create Date: 2025-05-28 18:13:27.856879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff449acc12b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drillposition', sa.Column('white_minor_count', sa.Integer(), nullable=True))
    op.add_column('drillposition', sa.Column('black_minor_count', sa.Integer(), nullable=True))
    op.add_column('drillposition', sa.Column('white_rook_count', sa.Integer(), nullable=True))
    op.add_column('drillposition', sa.Column('black_rook_count', sa.Integer(), nullable=True))
    op.add_column('drillposition', sa.Column('white_queen', sa.Boolean(), nullable=True))
    op.add_column('drillposition', sa.Column('black_queen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drillposition', 'black_queen')
    op.drop_column('drillposition', 'white_queen')
    op.drop_column('drillposition', 'black_rook_count')
    op.drop_column('drillposition', 'white_rook_count')
    op.drop_column('drillposition', 'black_minor_count')
    op.drop_column('drillposition', 'white_minor_count')
    # ### end Alembic commands ###
